#!/usr/bin/env ruby
# Even Fibonacci Numbers
# Project Euler, Problem 2
# http://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will
# be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.
require_relative 'lib/lazy_series'

module ProjectEuler
  module_function
  def problem_2(max: 4e6)
    LazySeries::Fibonacci.terms.even.below(max).sum
  end
end

if __FILE__ == $0
  puts ProjectEuler.problem_2
end
